language: java

jdk:
  - openjdk11

script: mvn deploy --settings settings.xml

# See https://github.com/travis-ci/travis-ci/issues/6593, sometime Maven Central isn't accessible to non-sudo users
sudo: true
